name: Sync Upstream to mine

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: merge diygod/master to mine
      shell: bash
      run: |
        set -eux
        git remote add -f diygod "https://github.com/DIYgod/RSSHub.git"
        git checkout mine
        git merge --ff-only diygod/master
        git push
