name: Sync Upstream to mine

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        name: Sync upstream/master to mine
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          owner: DIYgod
          base: master
          head: mine
          auto_approve: true
