name: Sync Upstream to mine

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Fetch upstream changes
        run: |
          git remote add -f upstream https://github.com/DIYgod/RSSHub.git
          git fetch upstream
      - name: Merge upstream/master changes
        run: |
          git merge --ff-only upstream/master
      - name: Push changes to mine
        run: |
          git push origin HEAD:mine
